"""removed Membership orm class

Revision ID: 113e8bbc98bd
Revises: ba6e11f08889
Create Date: 2026-04-24 20:55:22.810063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113e8bbc98bd'
down_revision: Union[str, Sequence[str], None] = 'ba6e11f08889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.drop_constraint(op.f('fk_group_owner'), 'groups', type_='foreignkey')
    op.drop_table('memberships')
    op.create_foreign_key(None, 'groups', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('fk_group_owner'), 'groups', 'memberships', ['owner_id'], ['id'])
    op.create_table('memberships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('memberships_group_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('memberships_pkey'))
    )
    op.drop_table('group_members')
    # ### end Alembic commands ###
