"""added Group and Memebership models, added relationship between User model and Membership model.

Revision ID: 3b245bd0e908
Revises: c7eac666ca8b
Create Date: 2026-04-23 19:03:27.116170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b245bd0e908'
down_revision: Union[str, Sequence[str], None] = 'c7eac666ca8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.add_column('groups' ,sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_group_owner', 'groups', 'memberships', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memberships')
    op.drop_table('groups')
    # ### end Alembic commands ###
