"""Add cascade delete for polls

Revision ID: 7863e6aaf0a9
Revises: 8ccf7e87fe20
Create Date: 2026-04-29 18:52:14.466148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7863e6aaf0a9'
down_revision: Union[str, Sequence[str], None] = '8ccf7e87fe20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poll_options', 'poll_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('poll_options_poll_id_fkey'), 'poll_options', type_='foreignkey')
    op.create_foreign_key(None, 'poll_options', 'polls', ['poll_id'], ['id'], ondelete='CASCADE')
    op.alter_column('poll_responses', 'poll_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('poll_responses', 'option_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('poll_responses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('poll_responses_option_id_fkey'), 'poll_responses', type_='foreignkey')
    op.drop_constraint(op.f('poll_responses_poll_id_fkey'), 'poll_responses', type_='foreignkey')
    op.create_foreign_key(None, 'poll_responses', 'poll_options', ['option_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'poll_responses', 'polls', ['poll_id'], ['id'], ondelete='CASCADE')
    op.alter_column('polls', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('polls', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('polls', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('polls', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'poll_responses', type_='foreignkey')
    op.drop_constraint(None, 'poll_responses', type_='foreignkey')
    op.create_foreign_key(op.f('poll_responses_poll_id_fkey'), 'poll_responses', 'polls', ['poll_id'], ['id'])
    op.create_foreign_key(op.f('poll_responses_option_id_fkey'), 'poll_responses', 'poll_options', ['option_id'], ['id'])
    op.alter_column('poll_responses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('poll_responses', 'option_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('poll_responses', 'poll_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'poll_options', type_='foreignkey')
    op.create_foreign_key(op.f('poll_options_poll_id_fkey'), 'poll_options', 'polls', ['poll_id'], ['id'])
    op.alter_column('poll_options', 'poll_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
