"""removed owned_groups column from User model.

Revision ID: 9837e91d4aef
Revises: 113e8bbc98bd
Create Date: 2026-04-24 21:24:24.151348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9837e91d4aef'
down_revision: Union[str, Sequence[str], None] = '113e8bbc98bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
