"""added some changes to the group and members columns in Group and Memeberships models

Revision ID: ba6e11f08889
Revises: 3b245bd0e908
Create Date: 2026-04-23 20:44:35.105627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba6e11f08889'
down_revision: Union[str, Sequence[str], None] = '3b245bd0e908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
