"""added black_listed column to RefreshToken Model

Revision ID: c7eac666ca8b
Revises: 0cb93cbbfee9
Create Date: 2026-04-15 18:03:18.385689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7eac666ca8b'
down_revision: Union[str, Sequence[str], None] = '0cb93cbbfee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('blacked_listed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'blacked_listed')
    # ### end Alembic commands ###
